### ISSUE TITLE
Browser is not launched

### ISSUE THREAD

**Issue by vtmocanu** [BalliAsghar/mailsy-alfred#1]
Get Mail works ok, it does fetch the mails, but when i press Enter on a received email nothing happens, no browser tab is opened.
Do you have any suggestions?
Thank you for sharing this workflow!

**Comment by BalliAsghar** [comment]
### could you possibly show logs from Alfred?
 
open Alfred's preferences to the correct workflow and click the bug in the top right of the workflow to display the debugger at the bottom of the screen. 
 
now try to open email, it should display logs, please share those logs.

**Comment by vtmocanu** [comment]
```
[08:09:45.064] Mailsy[Script Filter] Queuing argument '(null)'
[08:09:45.502] Mailsy[Script Filter] Script with argv '(null)' finished
[08:09:45.505] Mailsy[Script Filter] {
	"items": [
		{
			"title": "myemail@gmail.com - 3/27/2022, 9:08:02 AM",
			"subtitle": "Testing",
			"arg": "623fff45044c34f3c8fddaf1",
			"icon": {
				"path": "./icons/email.png"
			}
		}
	]
}
[08:09:50.393] Mailsy[Script Filter] Processing complete
[08:09:50.395] Mailsy[Script Filter] Passing output '623fff45044c34f3c8fddaf1' to Run Script
```

**Comment by BalliAsghar** [comment]
which Browser do you use? default browser?
It appears that the package I'm using to open an email only works with certain browsers.

[chrome](https://www.google.com/chrome) 
[firefox](https://www.mozilla.org/firefox)
[edge](https://www.microsoft.com/edge)

**Comment by BalliAsghar** [comment]
amend script  like this `./node_modules/.bin/run-node open.mjs "$1" && open ./email.html`

**Comment by BalliAsghar** [comment]
![gif](https://user-images.githubusercontent.com/14165223/160381395-14a6d028-aa24-4278-a1d3-37169ce5a56d.gif)

**Comment by BalliAsghar** [comment]
https://user-images.githubusercontent.com/14165223/160382066-58ba783b-ddc7-4381-b9a6-24ef5d6cba1c.mov

**Comment by vtmocanu** [comment]
First it complained obviously about not findind email.html, but i created it and it opened ok in my default firefox browser. So open worked.

**Comment by BalliAsghar** [comment]
So, everything is finally operational. Should I close the issue?

**Comment by vtmocanu** [comment]
This should be reopened, the workflow opened the email.html file that i created, not the email, the problem still persists. I cannot get the email to open in the browser.

I created /Users/myuser/stuff/nextcloud/sync/alfred/Alfred.alfredpreferences/workflows/user.workflow.00CF7DD7-AC2A-406B-9CAB-3638DDF0A237/email.html file manually and this file was opened in the browser, but not the actual email.

**Comment by BalliAsghar** [comment]
huh, what's the version of nodeJS you have installed?

**Comment by vtmocanu** [comment]
```
node --version
v16.13.0
```

**Comment by BalliAsghar** [comment]
delete the old one try this one, this should work! 🤞
[download workflow](https://github.com/BalliAsghar/mailsy-alfred/raw/BalliAsghar-patch-1/Mailsy.alfredworkflow)

**Comment by vtmocanu** [comment]
Yup, this one works!
Thank you very much for your quick support!
Just one side question: is it possible to open it in the current opened browser as a tab? At the moment it opens a new browser window, which doesn't really matter too much for me.
Thank you!

**Comment by BalliAsghar** [comment]
The package I was using previously opened in the currently active browser, but it wasn't working for you, so I'm using a native utility to open email, which I'm not that experienced with. So I'm not sure if it's doable or not.

**Comment by vtmocanu** [comment]
Cool, got it, thank you again for fixing and for the quick support.
