### ISSUE TITLE
Updated Alfred workflow?

### ISSUE THREAD

**Issue by luckman212** [BalliAsghar/mailsy-alfred#3]
Hi @BalliAsghar and thank you for the useful workflow! I've been using it with Alfred5 and it's been great. 

I saw you released a [new build 3.0.6](https://github.com/BalliAsghar/Mailsy/releases/tag/3.0.6) of mailsy, is there a straightforward way to incorporate this into the Alfred workflow? Or will you be pushing a new release of it? Thank you

**Comment by BalliAsghar** [comment]
> Hi @BalliAsghar and thank you for the useful workflow! I've been using it with Alfred5 and it's been great.
> 
> I saw you released a [new build 3.0.6](https://github.com/BalliAsghar/Mailsy/releases/tag/3.0.6) of mailsy, is there a straightforward way to incorporate this into the Alfred workflow? Or will you be pushing a new release of it? Thank you

Hello, @luckman212. That release is exclusively for Mailsy on the terminal, and the feature added in that release is only for the terminal.
